_target_: atria_datasets.pipelines.atria_data_pipeline.AtriaDataPipeline
data_dir: null
dataloader_config:
  _target_: atria_datasets.pipelines.atria_data_pipeline.DataloaderConfig
  train_batch_size: 64
  eval_batch_size: 64
  num_workers: 4
  pin_memory: true
  drop_last: false
preprocess_transforms:
  _target_: atria_core.transforms.base.DataTransformsDict
  train: null
  evaluation: null
use_validation_set_for_test: false
use_train_set_for_test: false
tar_sampling_chunk_size: 1000
enable_sharded_storage: false
shard_storage_type: WEBDATASET
num_processes: 8
max_shard_size: 100000
max_memory_per_actor: 524288000
max_concurrent_tasks_limit: 100
streaming_mode: false
dataset_splitting_enabled: false
split_ratio: 0.9
access_token: null
overwrite_existing_cached: false
overwrite_existing_shards: false
collate_fn: default_collate
defaults:
- _self_
- /dataset@dataset: null
- /batch_sampler@batch_samplers.train: null
- /batch_sampler@batch_samplers.evaluation: null
