_target_: atria_datasets.layout_analysis.doclaynet.DocLayNet
dataset_name: doclaynet
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
hf_repo: ds4sd/DocLayNet
hf_config_name: '2022.08'
