_target_: atria_datasets.document_classification.rvlcdip.RvlCdip
dataset_name: rvlcdip
config_name: image
max_train_samples: null
max_validation_samples: null
max_test_samples: null
load_ocr: false
type: default
