_target_: atria_datasets.document_classification.rvlcdip.RvlCdip
type: default
load_ocr: true
dataset_name: rvlcdip
config_name: image_with_ocr_1k
max_train_samples: 1000
max_validation_samples: 1000
max_test_samples: 1000
