_target_: atria_datasets.document_classification.rvlcdip.RvlCdip
_partial_: false
data_urls:
  labels/main/train.txt: https://huggingface.co/datasets/sasa3396/rvlcdip/resolve/main/data/tobacco3482_excluded/train.txt
  labels/main/test.txt: https://huggingface.co/datasets/sasa3396/rvlcdip/resolve/main/data/tobacco3482_excluded/test.txt
  labels/main/val.txt: https://huggingface.co/datasets/sasa3396/rvlcdip/resolve/main/data/tobacco3482_excluded/val.txt
  rvl-cdip.tar.gz: https://huggingface.co/datasets/rvl_cdip/resolve/main/data/rvl-cdip.tar.gz
  rvl-cdip-ocr.tar.gz: https://huggingface.co/datasets/sasa3396/rvlcdip/resolve/main/data/rvl-cdip-ocr.tar.gz
max_train_samples: null
max_validation_samples: null
max_test_samples: null
