_target_: atria_datasets.table_extraction.pubtables1m.PubTables1M
task: structure
dataset_name: pubtables1m
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
