_target_: atria_datasets.table_extraction.pubtables1m.PubTables1M
task: structure
dataset_name: pubtables1m
config_name: structure_1k
max_train_samples: 1000
max_validation_samples: 1000
max_test_samples: 1000
