_target_: atria_datasets.ser.wild_receipts.WildReceipts
dataset_name: wild_receipts
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
apply_reading_order_correction: true
