_target_: atria_datasets.image_classification.mnist.MNIST
hf_repo: ???
hf_config_name: ???
dataset_name: mnist
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
_partial_: false
