_target_: atria_datasets.image_classification.mnist.MNIST
hf_repo: ylecun/mnist
hf_config_name: mnist
dataset_name: mnist
config_name: mnist_1k
max_train_samples: 1000
max_test_samples: 1000
max_validation_samples: 1000
