_target_: atria_datasets.image_classification.cifar10_huggingface.HuggingfaceCifar10
hf_repo: ???
hf_config_name: ???
dataset_name: huggingface_cifar10
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
_partial_: false
