_target_: atria_datasets.image_classification.cifar10_huggingface.HuggingfaceCifar10
_partial_: false
hf_repo: ???
hf_config_name: ???
max_train_samples: null
max_validation_samples: null
max_test_samples: null
