_target_: atria_datasets.image_classification.cifar10_huggingface.HuggingfaceCifar10
hf_repo: uoft-cs/cifar10
hf_config_name: plain_text
dataset_name: huggingface_cifar10
config_name: plain_text_1k
max_train_samples: 1000
max_test_samples: 1000
max_validation_samples: 1000
