_target_: atria_datasets.ser.docile.Docile
_partial_: false
data_urls:
- https://docile-dataset-rossum.s3.eu-west-1.amazonaws.com/{access_token}/annotated-trainval.zip
- https://docile-dataset-rossum.s3.eu-west-1.amazonaws.com/{access_token}/test.zip
max_train_samples: null
max_validation_samples: null
max_test_samples: null
synthetic: false
overlap_threshold: 0.5
image_shape:
- 1024
- 1024
