_target_: atria_datasets.ser.docile.Docile
_partial_: false
max_train_samples: null
max_validation_samples: null
max_test_samples: null
synthetic: true
overlap_threshold: 0.5
image_shape:
- 1024
- 1024
type: lir
