_target_: atria_datasets.ser.docbank.DocBankLER
_partial_: false
dataset_name: docbank
config_name: 1k
max_train_samples: 1000
max_validation_samples: 1000
max_test_samples: 1000
max_words_per_sample: 4000
