_target_: atria_datasets.table_extraction.fintabnet.FinTabNet
_partial_: false
dataset_name: fintabnet
config_name: default
max_train_samples: null
max_validation_samples: null
max_test_samples: null
