_target_: atria_datasets.document_classification.tobacco3482.Tobacco3482
dataset_name: tobacco3482
config_name: image_with_ocr
max_train_samples: null
max_validation_samples: null
max_test_samples: null
load_ocr: true
