_target_: atria_datasets.document_classification.tobacco3482.Tobacco3482
_partial_: false
data_urls:
- https://huggingface.co/datasets/sasa3396/tobacco3482/resolve/main/data/tobacco3482.tar.gz
- https://huggingface.co/datasets/sasa3396/tobacco3482/resolve/main/data/tobacco3482_ocr.tar.gz
- https://huggingface.co/datasets/sasa3396/tobacco3482/resolve/main/data/train.txt
- https://huggingface.co/datasets/sasa3396/tobacco3482/resolve/main/data/test.txt
max_train_samples: null
max_validation_samples: null
max_test_samples: null
